export default data = {
  info: [
    {
      id: 1,
      images: [
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
      ],
      photo:
        'https://cdn.aarp.net/content/dam/aarp/entertainment/books/2020/10/1140-the-shining.imgcache.rev.web.300.462.jpg',
      category: 'Scariest Books',
      title: 'The Shining by Stephen King (1977)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '3.5',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '3.5',
      desc: "A recovering alcoholic and failed writer, Jack Torrance, his wife, Wendy, and their prescient young son, Danny, spend a blizzardy winter in the haunted Overlook Hotel where Jack gets cabin fever like nobody's business. You've seen the movie starring a crazed Jack Nicholson as Jack, but have you read the novel on which it was based? If not, do, say its many fans. “It's the ultimate ‘book was better than the movie’ conversation starter,” says Ron Block, branch manager of the Middleburg Heights Branch of the Cuyahoga County Public Library in Ohio. He adds, “It's the first book I ever threw across the room from terror.”",
    },
    {
      id: 2,
      images: [{imageURL: 'url'}],
      photo:
        'https://cdn.aarp.net/content/dam/aarp/entertainment/books/2020/10/1140-the-turn-of-the-screw.imgcache.rev.web.300.456.jpg',
      category: 'Scariest Books',
      title: 'The Turn of the Screw by Henry James (1898)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '4.2',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '4.2',
      desc: "A young woman is the governess for two disturbingly fearless and distinctly odd children, Miles and Flora, in a remote country home, Bly Manor, that seems bedeviled by mysterious doings and fiendish creatures. This timeless Gothic tale by the renowned Henry James (author of 1881's The Portrait of a Lady) first appeared as a serial in Collier's magazine in 1898, and is now a classic. “It still makes the hairs on my neck stand up,” Block says. “It hits all the notes, including ghostly apparitions, strangely behaved children, mysterious caretakers and a story that hits you hard.” ",
    },
    {
      id: 3,
      images: [{imageURL: 'url'}, {imageURL: 'url'}],
      photo:
        'https://cdn.aarp.net/content/dam/aarp/entertainment/books/2020/10/1140-the-haunting-of-mill-house.imgcache.rev.web.300.456.jpg',
      category: 'Scariest Books',
      title: 'The Haunting of Hill House by Shirley Jackson (1959)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '5.0',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '5',
      desc: "One of the most famous ghost stories in modern history by a master of the genre, Jackson's truly spooky tale spawned two feature films and a hit Netflix series in 2018. The premise: A group of four researchers stay in an old mansion to determine if there's any truth in rumors of its haunting — and then the tables terrifyingly turn when the house begins to want one of them as its own. It's touted by Rachel Conrad, a bookseller at Wellesley Books in Wellesley, Massachusetts, as “a classic ghost story and one that everyone should read at some point in their life.”",
    },
    {
      id: 4,
      images: [{imageURL: 'url'}, {imageURL: 'url'}, {imageURL: 'url'}],
      photo:
        'https://cdn.aarp.net/content/dam/aarp/entertainment/books/2020/10/1140-the-woman-in-black.imgcache.rev.web.300.456.jpg',
      category: 'Scariest Books',
      title: 'The Woman in Black by Susan Hill (1983)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '3.7',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '3.7',
      desc: "Another haunted house, this one in a small English town, features a rocking chair, a child's scream cutting through the fog and, of course, the mysterious Woman in Black. Lawyer Arthur Kipps visits the home of the late widow Alice Drablow to handle her estate, and experiences the ghost of a woman whose presence signals the imminent death of a child. This dark ghost story, turned into a hit play in London and a 2012 movie starring Daniel Radcliffe, is recommended by Pamela Klinger-Horne of Excelsior Bay Booksellers in Excelsior, Minnesota, who calls it “a traditional Gothic tale that will make you keep all the lights on.”",
    },
    {
      id: 5,
      images: [
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
      ],
      photo:
        'https://cdn.aarp.net/content/dam/aarp/entertainment/books/2020/10/1140-salems-lot.imgcache.rev.web.300.456.jpg',
      category: 'Scariest Books',
      title: "Salem's Lot by Stephen King (1975)",
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '4.6',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '4.6',
      desc: "This terrifying tale is only the second novel by King, but it's as frightening as any of his great works. We meet writer Ben Mears, who returns to the small Maine town where he grew up to study the history of a particularly disturbing house, now owned by a Kurt Barlow — a strange character who turns out to be an ancient vampire. A young boy becomes a vampire, too, followed by others, and the horror quickly escalates. The novel will “keep you up all night and looking over your shoulder in the day,” says Klinger-Horne. “It almost ended my babysitting career because I was too afraid to be alone in the house.”",
    },
    {
      id: 6,
      images: [
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
      ],
      photo:
        'https://cdn.aarp.net/content/dam/aarp/entertainment/books/2020/10/1140-a-head-full-of-ghosts.imgcache.rev.web.300.456.jpg',
      category: 'Scariest Books',
      title: 'A Head Full of Ghosts by Paul Tremblay (2015)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '2.7',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '2.7',
      desc: "If Stephen King says a book “scared the hell out of me,” as he did in a blurb about this story, you know it's a doozy. A teenage girl, Marjorie Barrett, appears to be losing her mind and is thought to be possessed by demons, then winds up on a reality show called The Possession, where even more horrifying devilment ensues. Years later, her sister Merry revisits the show to find out what really happened … and why. Conrad at Wellesley Books says, “It took me two tries to get through A Head Full of Ghosts. … It was so unsettling that I couldn't bring myself to finish it the first time around. The second time I tried reading it I could only do so in the morning, in full daylight.”",
    },
    {
      id: 7,
      images: [
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
      ],
      photo:
        'https://cdn.aarp.net/content/dam/aarp/entertainment/books/2020/10/1140-fever-dream.imgcache.rev.web.300.456.jpg',
      category: 'Scariest Books',
      title: 'Fever Dream by Samanta Schweblin (2017)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '4.3',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '4.3',
      desc: "Short-listed for the Man Booker International Prize, this chiller by an Argentine author begins with a woman dying in a clinic, confused about why she's there and interrogated by a young boy she doesn't know. She begins to recall a story: The boy's mother had taken her sick son to a healer, who tried to revive him by allowing half his soul to be taken over by a stranger's — a stranger who turns out to be a monster she somehow has to vanquish. “I think Fever Dream is one of the most terrifying books of all time,” says Hannah Robinson, a bookseller at Porter Square Books in Cambridge, Massachusetts. “The slow-burning suspense genuinely made me sweat while reading this creepy little novel.”",
    },
    {
      id: 8,
      images: [
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
      ],
      photo:
        'https://cdn.aarp.net/content/dam/aarp/entertainment/books/2020/10/1140-the-grownup.imgcache.rev.web.300.456.jpg',
      category: 'Scariest Books',
      title: 'The Grownup by Gillian Flynn (2015)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '3.1',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '3.1',
      desc: "A New York Times best seller and Edgar Award winner, this novella by the author of Gone Girl (famous for its twisty plot) was first featured in a short story collection as “What Do You Do?” It features a young woman working as a fake psychic who's hired by a wealthy woman to inspect her home because it may be haunted. The con artist soon begins to think that the apparitions she's seeing just might be real — especially when the woman's teenage son's behavior turns rather weird. Conrad says, “Flynn also does an expert job of making the reader wonder whether anything supernatural is happening at all or if it's all in the protagonist's head.”",
    },
    {
      id: 9,
      images: [
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
      ],
      photo:
        'https://cdn.aarp.net/content/dam/aarp/entertainment/books/2020/10/1140-the-only-good-indians.imgcache.rev.web.300.456.jpg',
      category: 'Scariest Books',
      title: 'The Only Good Indians by Stephen Graham Jones (2020)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '2.8',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '2.88',
      desc: "Years after they massacre a herd of elk on land they're not supposed to be hunting on, four friends find that they have become the hunted when the spirit of one of the elk comes back for them. Robinson's bookstore colleague Katherine Nazzara calls it “both a thrilling tale that will have you jumping at the slightest sound (I speak from experience), and a poignant look at cultural identity and what it's like to live in a world that's trying to kill you.” She adds, “I finished this book and immediately ordered two other novels by Stephen Graham Jones, because he is truly a master.” ",
    },
    {
      id: 10,
      images: [
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
      ],
      photo:
        'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1442713631l/3974._SY475_.jpg',
      category: 'Scariest Books',
      title: 'The Terror by Dan Simmons',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '3.9',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '3.9',
      desc: "The men on board HMS Terror have every expectation of triumph. As part of the 1845 Franklin Expedition, the first steam-powered vessels ever to search for the legendary Northwest Passage, they are as scientifically supported an enterprise as has ever set forth. As they enter a second summer in the Arctic Circle without a thaw, though, they are stranded in a nightmarish landscape of encroaching ice and darkness. Endlessly cold, with diminishing rations, 126 men fight to survive with poisonous food, a dwindling supply of coal, and ships buckling in the grip of crushing ice. But their real enemy is far more terrifying. There is something out there in the frigid darkness: an unseen predator stalking their ship, a monstrous terror constantly clawing to get in.When the expedition's leader, Sir John Franklin, meets a terrible death, Captain Francis Crozier takes command and leads his surviving crewmen on a last, desperate attempt to flee south across the ice. With them travels an Inuit woman who cannot speak and who may be the key to survival, or the harbinger of their deaths. But as another winter approaches, as scurvy and starvation grow more terrible, and as the terror on the ice stalks them southward, Crozier and his men begin to fear that there is no escape.",
    },
    {
      id: 11,
      images: [{imageURL: 'url'}, {imageURL: 'url'}, {imageURL: 'url'}],
      photo:
        'https://www.penguin.co.uk/content/dam/prh/books/107/1074171/9781787461079.jpg.transform/PRHDesktopWide_small/image.jpg',
      category: 'Funny books',
      title: 'Carry On, Jeeves by P. G. Wodehouse (1925)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '4.2',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '4.2',
      desc: 'No writer better conjures a specific period in history than P. G. Wodehouse. His name alone is synonymous with a vanished time of upper-class Edwardian England, when wars were won on cups of tea, cricket ruled the waves, and lunch was always soup and fish. And yet, his stories – and humour are timeless. Of them, none are funnier than those of bumbling Bertie Wooster and his bacon-saving butler Jeeves. Carry On, Jeeves starts the journey of Bertie, the what-hoing toff who, time and again, falls into the soup, only for Jeeves to fish him out. The Jeeves-Wooster relationship has a comic energy like none you’ll read again.',
    },
    {
      id: 12,
      images: [
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
      ],
      photo:
        'https://www.penguin.co.uk/content/dam/prh/books/107/1070115/9781407037783.jpg.transform/PRHDesktopWide_small/image.jpg',
      category: 'Funny books',
      title: 'I Feel Bad About My Neck by Nora Ephron (2006)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '4.5',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '4.5',
      desc: "Nora Ephron doesn’t like her neck, and that’s the premise to the opener of this delectably dry collection of essays by the brain behind When Harry Met Sally and Sleepless in Seattle. It’s really an ode to getting older, gracefully or not.With searing self-mockery, she delivers her hard-earned truths on all angles of womanhood, from why she hates her purse You start small … but within seconds, your purse has accumulated the debris of a lifetime to the joys of having children When your children are teenagers, it's important to have a dog so that someone in the house is happy to see you ",
    },
    {
      id: 13,
      images: [
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
      ],
      photo:
        'https://www.penguin.co.uk/content/dam/prh/books/273/273734/9780718179748.jpg.transform/PRHDesktopWide_small/image.jpg',
      category: 'Funny books',
      title: 'Grown Ups by Marian Keyes (2020)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '3.8',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '3.8',
      desc: 'There are few modern writers more effortlessly funny than Marian Keyes, and the Irish writer is never better than in her tragicomic family epic, Grown Ups. Her latest novel, about the secrets families keep and the intense pressures of social mores, follows Johnny and Jessie Casey, whose ongoing masquerade as a perfect family is upended when Johnny’s sister-in-law suffers a concussion and begins to spill the secrets kept between the two sets of Caseys. The messy and hilarious aftermath between the young families forces them – and, in Keyes’ typically relatable style, forces readers too – to confront their lives. It’s a complex, tangled portrait of humanity, as heartbreakingly poignant as it is riotously funny – and perhaps Keyes’ best work yet.',
    },
    {
      id: 14,
      images: [
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
      ],
      photo:
        'https://www.penguin.co.uk/content/dam/prh/books/570/57022/9780141182599.jpg.transform/PRHDesktopWide_small/image.jpg',
      category: 'Funny books',
      title: 'Lucky Jim by Kingsley Amis (1954)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '3.6',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '3.6',
      desc: 'If you want to read the funniest description of a hangover ever put to paper, read Lucky Jim. It’s too long to reproduce here wholesale, but includes the immortal (if not gut-churning) words: His mouth had been used as a latrine by some small creature of the night and then as its mausoleum.Kingsley Amis had a wicked sense of humour, and Lucky Jim is his greatest gag. It’s a campus novel about a misanthropic history lecturer who’s accidentally landed a job at a red-brick university. He doesn’t fit. He hates the world he’s fallen into, and would far rather flirt and drink than suffer the intolerable pomposity of academic life. So he is forced to do both.',
    },
    {
      id: 15,
      images: [
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
      ],
      photo:
        'https://www.penguin.co.uk/content/dam/prh/books/306/306118/9780141046426.jpg.transform/PRHDesktopWide_small/image.jpg',
      category: 'Funny books',
      title: 'The Secret Diary of Adrian Mole Aged 13 ¾ by Sue Townsend (1982)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '2.7',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '2.7',
      desc: "Not for nothing was this one of the biggest-selling books of the 1980s. From the confines of his parents' Leicester semi, Adrian Mole – the Pepys of modern Leicestershire – records his melancholy musings, lonely obsessions, the slow growth of his 'thing' and the 'funny feelings' he gets when he thinks about the wobbling chest of his life's great love, Pandora Braithwaite.But Townsend’s genius lay not only in her sly social observations and weirdly-accurate insight into the mind of a teenage boy, but her genius for one-liners like: My skin is dead good. I think it must be a combination of being in love and Lucozade. Or: I have realised I have never seen a dead body or a real female nipple. This is what comes of living in a cul-de-sac.",
    },
    {
      id: 16,
      images: [{imageURL: 'url'}, {imageURL: 'url'}],
      photo:
        'https://www.penguin.co.uk/content/dam/prh/books/245/24575/9780141939230.jpg.transform/PRHDesktopWide_small/image.jpg',
      category: 'Funny books',
      title: 'White Teeth by Zadie Smith (1999)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '4.4',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '4.4',
      desc: "One of the most written about books in modern British literature, White Teeth is Zadie Smith's widely ambitious saga about two boys rebelling against their families as they try to figure out who they are in a world riven by racial and cultural differences.Bouncing back and forth between the Second World War and the 1990s, it covers a phantasmagoria of subjects, from war to friendship, family to love, racial identity to belonging (and much more in between). In short, White Teeth is a rollercoaster of a book. But unlike what can happen in novels with interweaving storylines spanning a long period of time, all are equally spellbinding – and equally hilarious, too.",
    },
    {
      id: 17,
      images: [
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
      ],
      photo:
        'https://www.penguin.co.uk/content/dam/prh/books/603/60349/9780141920146.jpg.transform/PRHDesktopWide_small/image.jpg',
      category: 'Funny books',
      title:
        'The Life and Opinions of Tristram Shandy, Gentleman by Laurence Sterne (1759)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '4.6',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '4.6',
      desc: "Poor Tristram Shandy. If it weren't for his mother asking his father if he'd remember to wind the clock during the key stage of his conception, he might not have had such a bum deal in life. Or perhaps it was the foolish 'man-midwife' who crushed his nose with the forceps at birth. Or the chambermaid who inadvertently circumcised him with a sash window. Provocative, profane and utterly preposterous, Tristram Shandy is a novel about a man trying to make sense of his life, foraging through his family history to understand his own fate. Trouble is, he has a crippling weakness for digression (at one point he discovers with mock-horror that, 200 pages into his novel, he has got no farther than to my first day's life",
    },
    {
      id: 18,
      images: [
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
      ],
      photo:
        'https://www.penguin.co.uk/content/dam/prh/books/289/289979/9780241243503.jpg.transform/PRHDesktopWide_small/image.jpg',
      category: 'Funny books',
      title: 'The Wangs Vs. The World by Jade Chang (2016)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '3.7',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '3.7',
      desc: 'Charles Wang was a wealthy Chinese-American make-up tycoon until the 2008 financial crisis blew up in his face. Now he’s broke and in a funk. So he takes his wife and three very-different teenage kids on a road trip across America to reconnect with each other. But what starts as a road trip turns into a roots trip. They end up in China.Chang’s richly comic first novel is a wild ride: funny, endearing, wide-eyed and endlessly clever. It is a comedy about racial identity and belonging and what it is to call a place home.',
    },
    {
      id: 19,
      images: [
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
      ],
      photo:
        'https://www.penguin.co.uk/content/dam/prh/books/110/1101015/9781787533202.jpg.transform/PRHDesktopWide_small/image.jpg',
      category: 'Funny books',
      title: 'The Hitchhiker’s Guide to the Galaxy by Douglas Adams (1979)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '3.9',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '3.9',
      desc: "Simply, the most famous comedy science-fiction book ever written (not a great deal of competition in that genre, granted). In many ways, The Hitchhiker's Guide... is a literary genre unto itself: piercingly mischievous, squintingly ironic, keenly observant and beautifully idealistic… and all set in space. In an electron shell, it’s about a man called Arthur Dent and his alien friend Ford Prefect who wander the galaxy after the Earth is blown up to make way for a hyperspace bypass. They meet various characters along the way, including a manically depressed robot who saves their lives by striking up a casual conversation with the enemy spaceship’s computer and thereby unintentionally talking it into depression and then suicide.",
    },
    {
      id: 20,
      images: [
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
        {imageURL: 'url'},
      ],
      photo:
        'https://www.penguin.co.uk/content/dam/prh/books/101/1010/9780141907178.jpg.transform/PRHDesktopWide_small/image.jpg',
      category: 'Funny books',
      title: 'Scoop by Evelyn Waugh (1938)',
      published_From: 'istudio',
      published_Data: '24 March 2019',
      Rating: '5.0',
      completed: false,
      audio: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      stars: '5.0',
      desc: 'There’s a side-story in Scoop where a journalist is dispatched by train to cover a revolution in the Balkan states. He falls asleep and wakes in the wrong country and, oblivious to his mistake, heads straight for a hotel where he  off a thousand-word story about barricades in the streets, flaming churches, machine guns answering the rattle of his typewriter Despite it being totally made up, his story spurs a Fleet Street feeding frenzy for his phantom revolution, sparking a real one in its place. There,Waugh concludes, is the power of the press for you.',
    },
  ],
};
